### ISSUE TITLE
依赖下载失败，sdk地址证书过期。

### ISSUE THREAD

**Issue by PlatON-Fans** [PlatONnetwork/ATON-Android#141]
build时执行 gradle assembleReleaseX 报错Could not get resource 'https://sdk.platon.network/nexus/content/groups/public/com/platon/client/crypto/0.6.0-android/crypto-0.6.0-android.pom'.

![QQ截图20190716124302](https://user-images.githubusercontent.com/52944960/61266826-25bdbc00-a7c8-11e9-937f-fcf9c07c9d25.png)

地址https://sdk.platon.network/nexus/content/groups/public/com/platon/client/crypto/0.6.0-android/crypto-0.6.0-android.pom  证书过期了。
![QQ截图20190716125633](https://user-images.githubusercontent.com/52944960/61267137-2dca2b80-a7c9-11e9-9b06-29c92dd75c75.png)

**Comment by danielgogo** [comment]
谢谢指出，已经重签了
