### ISSUE TITLE
 gradle assembleReleaseX failed

### ISSUE THREAD

**Issue by aviland** [PlatONnetwork/ATON-Android#623]
failed message:  
gradle assembleReleaseX

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Script 'E:\codes\IdeaProjects\gitee.com\HAYPO\ATON-Android\jacoco-report.gradle' line: 26

* What went wrong:
A problem occurred evaluating script.
> Cannot set the value of read-only property 'classDirectories' for task ':wallet:jacocoTestReport' of type org.gradle.testing.jacoco.tasks.JacocoReport.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':wallet'.
> compileSdkVersion is not specified.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.8/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1s

**Comment by biganxin** [comment]
@danielgogo  Help with the answer，Thanks

**Comment by chenxiaodai** [comment]
solve https://github.com/PlatONnetwork/ATON-Android/pull/625
